#!/bin/bash
# ralph.sh — Primal Dad Weekly Check-In Runner
# Triggered every Sunday via ralph-loop
# Spawns a Claude Code instance to run the weekly check-in flow

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
PRD_FILE="$SCRIPT_DIR/prd.json"
PROGRESS_FILE="$SCRIPT_DIR/progress.txt"
CLAUDE_MD="$SCRIPT_DIR/CLAUDE.md"

# Initialize progress file if it doesn't exist
if [ ! -f "$PROGRESS_FILE" ]; then
  echo "# Primal Dad Check-In Progress Log" > "$PROGRESS_FILE"
  echo "# Auto-generated by ralph.sh" >> "$PROGRESS_FILE"
  echo "" >> "$PROGRESS_FILE"
fi

# Log start
echo "[$(date -Iseconds)] Starting weekly check-in" >> "$PROGRESS_FILE"

cd "$PROJECT_DIR"

# Run Claude Code with the check-in task
# --print for non-interactive mode, pointing at the ralph CLAUDE.md for agent instructions
claude --print \
  --system-prompt "$(cat "$CLAUDE_MD")" \
  "Run the Primal Dad weekly check-in. Read prd.json acceptance criteria from ralph/prd.json and follow every step. Today is $(date +%Y-%m-%d). Current ISO week: $(date +%V)."

# Log completion
echo "[$(date -Iseconds)] Check-in completed" >> "$PROGRESS_FILE"
